apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: develop

resources:
- ../base

patchesStrategicMerge:
- ingress.yaml
- deployment-patch.yaml

images:
- name: docker.jmeks20.reisys.io/infra-test
  newTag: latest-2
